<a href="https://colab.research.google.com/github/yousufislam191/Machine-Learning-Practice/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Practice

In [ ]:
import numpy as np
from time import process_time

### List vs Numpy - Time Taken

### Time Taken by a List **10000 loop**

In [ ]:
python_list = [i for i in range(10)]
start_time = process_time()

python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.00011315999999972348


### Time Taken by a Numpy for **10000 loop**

In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()

np_array += 5
end_time = process_time()

print(end_time - start_time)

0.00011012999999948647


### Create a numpy array with 3 rows and 4 columns where value will be zero

In [ ]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Create a numpy array with 3 rows and 4 columns where value will be one

In [ ]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Create a numpy array with 3 rows and 4 columns where value will be customized

In [ ]:
print(np.full((3, 4), 5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### Create an Identity Metrix

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### create a numpy array with random values

In [ ]:
print(np.random.random((3,4)))

[[0.8692405  0.11047004 0.31403077 0.02645157]
 [0.07027164 0.77127344 0.18348194 0.81043174]
 [0.02379441 0.87215181 0.92882569 0.04877942]]


### numpy random integer value array within a specific range 5 to 12

In [ ]:
print(np.random.randint(5, 12, (3,4)))

[[ 9 10 10  9]
 [ 7  7 10  5]
 [ 7  9  7  6]]


### array of evenly spaced values
specifying the number of values required

In [ ]:
print(np.linspace(10, 40, 7))

[10. 15. 20. 25. 30. 35. 40.]


### array of evenly spaced values
specifying the step

In [ ]:
print(np.arange(10, 40, 7))

[10 17 24 31 38]


### convert a list to numpy array

In [ ]:
list1 = [10, 20, 30, 40, 50]
first_type = type(list1)
print("First Print: ", list1, first_type)

np_array = np.array(list1)
second_type = type(np_array)
print("Second Print: ", np_array, second_type)

First Print:  [10, 20, 30, 40, 50] <class 'list'>
Second Print:  [10 20 30 40 50] <class 'numpy.ndarray'>


### Analysing a numpy array

In [ ]:
c = np.random.randint(10, 90, (5,5))
print(c)

[[43 68 43 57 35]
 [26 59 35 75 36]
 [36 68 52 24 62]
 [63 18 72 13 64]
 [19 89 78 63 24]]


In [ ]:
# array dimention
print(c.shape)

(5, 5)


In [ ]:
# number of dimention
print(c.ndim)

2


In [ ]:
# number of element in an array
print(c.size)

25


In [ ]:
# checking the type of the values in the array
print(c.dtype)

int64


### Mathematical Operations on a numpy array

In [39]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # it will concatinate this list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [48]:
a = np.random.randint(1,10, (4,4))
print("Arrary of A: \n", a)

b = np.random.randint(20,30, (4,4))
print("\nArrary of B: \n", b)

# print("\nArrary of Addition: \n", a+b)
# print("\nArrary of Substraction: \n", a-b)
# print("\nArrary of Multiplication: \n", a*b)
# print("\nArrary of Divition: \n", a/b)

print("\nArrary of Addition: \n", np.add(a,b))
print("\nArrary of Substraction: \n", np.subtract(a,b))
print("\nArrary of Multiplication: \n", np.multiply(a,b))
print("\nArrary of Divition: \n", np.divide(a,b))

Arrary of A: 
 [[2 4 5 5]
 [6 2 1 7]
 [5 3 1 2]
 [3 7 2 5]]

Arrary of B: 
 [[23 24 25 29]
 [25 24 29 27]
 [23 29 23 21]
 [21 24 26 27]]

Arrary of Addition: 
 [[25 28 30 34]
 [31 26 30 34]
 [28 32 24 23]
 [24 31 28 32]]

Arrary of Substraction: 
 [[-21 -20 -20 -24]
 [-19 -22 -28 -20]
 [-18 -26 -22 -19]
 [-18 -17 -24 -22]]

Arrary of Multiplication: 
 [[ 46  96 125 145]
 [150  48  29 189]
 [115  87  23  42]
 [ 63 168  52 135]]

Arrary of Divition: 
 [[0.08695652 0.16666667 0.2        0.17241379]
 [0.24       0.08333333 0.03448276 0.25925926]
 [0.2173913  0.10344828 0.04347826 0.0952381 ]
 [0.14285714 0.29166667 0.07692308 0.18518519]]


### Array Manipulation

In [53]:
a = np.random.randint(1,10, (2,3))
print(a)
print(a.shape)

# tranpose the a matrix
print("\n Transpose Matrix:\n", np.transpose(a))
print("\n Transpose Matrix using T:\n", a.T)

[[4 2 4]
 [3 8 7]]
(2, 3)

 Transpose Matrix:
 [[4 3]
 [2 8]
 [4 7]]

 Transpose Matrix using T:
 [[4 3]
 [2 8]
 [4 7]]


In [55]:
# reshape matrix
array = np.random.randint(1,10, (2,3))
print("\n Main Matrix:\n", array)
print("\n Reshape Matrix:\n", array.reshape(3,2))


 Main Matrix:
 [[3 2 1]
 [7 1 1]]

 Reshape Matrix:
 [[3 2]
 [1 7]
 [1 1]]
